/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HumanRouteImport } from './routes/human'
import { Route as VerifierRouteImport } from './routes/verifier'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as HumanActivityRouteImport } from './routes/human.activity'
import { Route as HumanDashboardRouteImport } from './routes/human.dashboard'
import { Route as HumanIdentityRouteImport } from './routes/human.identity'
import { Route as HumanSettingsRouteImport } from './routes/human.settings'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginHumanRouteImport } from './routes/login.human'
import { Route as LoginVerifierRouteImport } from './routes/login.verifier'
import { Route as VerifierActivityRouteImport } from './routes/verifier.activity'
import { Route as VerifierDashboardRouteImport } from './routes/verifier.dashboard'
import { Route as VerifierPaymentsRouteImport } from './routes/verifier.payments'
import { Route as VerifierSettingsRouteImport } from './routes/verifier.settings'
import { Route as VerifierVerifyRouteImport } from './routes/verifier.verify'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiV1AgentsRouteImport } from './routes/api/v1/agents'
import { Route as ApiV1CredentialsRouteImport } from './routes/api/v1/credentials'
import { Route as ApiV1DigilockerRouteImport } from './routes/api/v1/digilocker'
import { Route as ApiV1IntegrationsRouteImport } from './routes/api/v1/integrations'
import { Route as ApiV1TransactionsRouteImport } from './routes/api/v1/transactions'
import { Route as HumanCredentialsIndexRouteImport } from './routes/human.credentials.index'
import { Route as HumanCredentialsAddRouteImport } from './routes/human.credentials.add'
import { Route as VerifierAgentsIndexRouteImport } from './routes/verifier.agents.index'
import { Route as VerifierAgentsAgentIdRouteImport } from './routes/verifier.agents.$agentId'
import { Route as ApiV1AgentsAgentIdRouteImport } from './routes/api/v1/agents.$agentId'
import { Route as ApiV1VerifyAgeRouteImport } from './routes/api/v1/verify/age'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanRoute = HumanRouteImport.update({
  id: '/human',
  path: '/human',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierRoute = VerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanActivityRoute = HumanActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => HumanRoute,
} as any)
const HumanDashboardRoute = HumanDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HumanRoute,
} as any)
const HumanIdentityRoute = HumanIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => HumanRoute,
} as any)
const HumanSettingsRoute = HumanSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HumanRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginHumanRoute = LoginHumanRouteImport.update({
  id: '/login/human',
  path: '/login/human',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifierRoute = LoginVerifierRouteImport.update({
  id: '/login/verifier',
  path: '/login/verifier',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierActivityRoute = VerifierActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierDashboardRoute = VerifierDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierPaymentsRoute = VerifierPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierSettingsRoute = VerifierSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierVerifyRoute = VerifierVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => VerifierRoute,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AgentsRoute = ApiV1AgentsRouteImport.update({
  id: '/api/v1/agents',
  path: '/api/v1/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CredentialsRoute = ApiV1CredentialsRouteImport.update({
  id: '/api/v1/credentials',
  path: '/api/v1/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DigilockerRoute = ApiV1DigilockerRouteImport.update({
  id: '/api/v1/digilocker',
  path: '/api/v1/digilocker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IntegrationsRoute = ApiV1IntegrationsRouteImport.update({
  id: '/api/v1/integrations',
  path: '/api/v1/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TransactionsRoute = ApiV1TransactionsRouteImport.update({
  id: '/api/v1/transactions',
  path: '/api/v1/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanCredentialsIndexRoute = HumanCredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => HumanRoute,
} as any)
const HumanCredentialsAddRoute = HumanCredentialsAddRouteImport.update({
  id: '/credentials/add',
  path: '/credentials/add',
  getParentRoute: () => HumanRoute,
} as any)
const VerifierAgentsIndexRoute = VerifierAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => VerifierRoute,
} as any)
const VerifierAgentsAgentIdRoute = VerifierAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => VerifierRoute,
} as any)
const ApiV1AgentsAgentIdRoute = ApiV1AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => ApiV1AgentsRoute,
} as any)
const ApiV1VerifyAgeRoute = ApiV1VerifyAgeRouteImport.update({
  id: '/api/v1/verify/age',
  path: '/api/v1/verify/age',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/human': typeof HumanRouteWithChildren
  '/verifier': typeof VerifierRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/human/activity': typeof HumanActivityRoute
  '/human/dashboard': typeof HumanDashboardRoute
  '/human/identity': typeof HumanIdentityRoute
  '/human/settings': typeof HumanSettingsRoute
  '/login/human': typeof LoginHumanRoute
  '/login/verifier': typeof LoginVerifierRoute
  '/verifier/activity': typeof VerifierActivityRoute
  '/verifier/dashboard': typeof VerifierDashboardRoute
  '/verifier/payments': typeof VerifierPaymentsRoute
  '/verifier/settings': typeof VerifierSettingsRoute
  '/verifier/verify': typeof VerifierVerifyRoute
  '/login/': typeof LoginIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/v1/agents': typeof ApiV1AgentsRouteWithChildren
  '/api/v1/credentials': typeof ApiV1CredentialsRoute
  '/api/v1/digilocker': typeof ApiV1DigilockerRoute
  '/api/v1/integrations': typeof ApiV1IntegrationsRoute
  '/api/v1/transactions': typeof ApiV1TransactionsRoute
  '/human/credentials/add': typeof HumanCredentialsAddRoute
  '/verifier/agents/$agentId': typeof VerifierAgentsAgentIdRoute
  '/human/credentials/': typeof HumanCredentialsIndexRoute
  '/verifier/agents/': typeof VerifierAgentsIndexRoute
  '/api/v1/agents/$agentId': typeof ApiV1AgentsAgentIdRoute
  '/api/v1/verify/age': typeof ApiV1VerifyAgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/human': typeof HumanRouteWithChildren
  '/verifier': typeof VerifierRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/human/activity': typeof HumanActivityRoute
  '/human/dashboard': typeof HumanDashboardRoute
  '/human/identity': typeof HumanIdentityRoute
  '/human/settings': typeof HumanSettingsRoute
  '/login/human': typeof LoginHumanRoute
  '/login/verifier': typeof LoginVerifierRoute
  '/verifier/activity': typeof VerifierActivityRoute
  '/verifier/dashboard': typeof VerifierDashboardRoute
  '/verifier/payments': typeof VerifierPaymentsRoute
  '/verifier/settings': typeof VerifierSettingsRoute
  '/verifier/verify': typeof VerifierVerifyRoute
  '/login': typeof LoginIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/v1/agents': typeof ApiV1AgentsRouteWithChildren
  '/api/v1/credentials': typeof ApiV1CredentialsRoute
  '/api/v1/digilocker': typeof ApiV1DigilockerRoute
  '/api/v1/integrations': typeof ApiV1IntegrationsRoute
  '/api/v1/transactions': typeof ApiV1TransactionsRoute
  '/human/credentials/add': typeof HumanCredentialsAddRoute
  '/verifier/agents/$agentId': typeof VerifierAgentsAgentIdRoute
  '/human/credentials': typeof HumanCredentialsIndexRoute
  '/verifier/agents': typeof VerifierAgentsIndexRoute
  '/api/v1/agents/$agentId': typeof ApiV1AgentsAgentIdRoute
  '/api/v1/verify/age': typeof ApiV1VerifyAgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/human': typeof HumanRouteWithChildren
  '/verifier': typeof VerifierRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/human/activity': typeof HumanActivityRoute
  '/human/dashboard': typeof HumanDashboardRoute
  '/human/identity': typeof HumanIdentityRoute
  '/human/settings': typeof HumanSettingsRoute
  '/login/human': typeof LoginHumanRoute
  '/login/verifier': typeof LoginVerifierRoute
  '/verifier/activity': typeof VerifierActivityRoute
  '/verifier/dashboard': typeof VerifierDashboardRoute
  '/verifier/payments': typeof VerifierPaymentsRoute
  '/verifier/settings': typeof VerifierSettingsRoute
  '/verifier/verify': typeof VerifierVerifyRoute
  '/login/': typeof LoginIndexRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/v1/agents': typeof ApiV1AgentsRouteWithChildren
  '/api/v1/credentials': typeof ApiV1CredentialsRoute
  '/api/v1/digilocker': typeof ApiV1DigilockerRoute
  '/api/v1/integrations': typeof ApiV1IntegrationsRoute
  '/api/v1/transactions': typeof ApiV1TransactionsRoute
  '/human/credentials/add': typeof HumanCredentialsAddRoute
  '/verifier/agents/$agentId': typeof VerifierAgentsAgentIdRoute
  '/human/credentials/': typeof HumanCredentialsIndexRoute
  '/verifier/agents/': typeof VerifierAgentsIndexRoute
  '/api/v1/agents/$agentId': typeof ApiV1AgentsAgentIdRoute
  '/api/v1/verify/age': typeof ApiV1VerifyAgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/human'
    | '/verifier'
    | '/api/health'
    | '/human/activity'
    | '/human/dashboard'
    | '/human/identity'
    | '/human/settings'
    | '/login/human'
    | '/login/verifier'
    | '/verifier/activity'
    | '/verifier/dashboard'
    | '/verifier/payments'
    | '/verifier/settings'
    | '/verifier/verify'
    | '/login/'
    | '/api/public/mcp'
    | '/api/v1/agents'
    | '/api/v1/credentials'
    | '/api/v1/digilocker'
    | '/api/v1/integrations'
    | '/api/v1/transactions'
    | '/human/credentials/add'
    | '/verifier/agents/$agentId'
    | '/human/credentials/'
    | '/verifier/agents/'
    | '/api/v1/agents/$agentId'
    | '/api/v1/verify/age'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/human'
    | '/verifier'
    | '/api/health'
    | '/human/activity'
    | '/human/dashboard'
    | '/human/identity'
    | '/human/settings'
    | '/login/human'
    | '/login/verifier'
    | '/verifier/activity'
    | '/verifier/dashboard'
    | '/verifier/payments'
    | '/verifier/settings'
    | '/verifier/verify'
    | '/login'
    | '/api/public/mcp'
    | '/api/v1/agents'
    | '/api/v1/credentials'
    | '/api/v1/digilocker'
    | '/api/v1/integrations'
    | '/api/v1/transactions'
    | '/human/credentials/add'
    | '/verifier/agents/$agentId'
    | '/human/credentials'
    | '/verifier/agents'
    | '/api/v1/agents/$agentId'
    | '/api/v1/verify/age'
  id:
    | '__root__'
    | '/'
    | '/human'
    | '/verifier'
    | '/api/health'
    | '/human/activity'
    | '/human/dashboard'
    | '/human/identity'
    | '/human/settings'
    | '/login/human'
    | '/login/verifier'
    | '/verifier/activity'
    | '/verifier/dashboard'
    | '/verifier/payments'
    | '/verifier/settings'
    | '/verifier/verify'
    | '/login/'
    | '/api/public/mcp'
    | '/api/v1/agents'
    | '/api/v1/credentials'
    | '/api/v1/digilocker'
    | '/api/v1/integrations'
    | '/api/v1/transactions'
    | '/human/credentials/add'
    | '/verifier/agents/$agentId'
    | '/human/credentials/'
    | '/verifier/agents/'
    | '/api/v1/agents/$agentId'
    | '/api/v1/verify/age'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HumanRoute: typeof HumanRouteWithChildren
  VerifierRoute: typeof VerifierRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  LoginHumanRoute: typeof LoginHumanRoute
  LoginVerifierRoute: typeof LoginVerifierRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiV1AgentsRoute: typeof ApiV1AgentsRouteWithChildren
  ApiV1CredentialsRoute: typeof ApiV1CredentialsRoute
  ApiV1DigilockerRoute: typeof ApiV1DigilockerRoute
  ApiV1IntegrationsRoute: typeof ApiV1IntegrationsRoute
  ApiV1TransactionsRoute: typeof ApiV1TransactionsRoute
  ApiV1VerifyAgeRoute: typeof ApiV1VerifyAgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human': {
      id: '/human'
      path: '/human'
      fullPath: '/human'
      preLoaderRoute: typeof HumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier': {
      id: '/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof VerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human/activity': {
      id: '/human/activity'
      path: '/activity'
      fullPath: '/human/activity'
      preLoaderRoute: typeof HumanActivityRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/dashboard': {
      id: '/human/dashboard'
      path: '/dashboard'
      fullPath: '/human/dashboard'
      preLoaderRoute: typeof HumanDashboardRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/identity': {
      id: '/human/identity'
      path: '/identity'
      fullPath: '/human/identity'
      preLoaderRoute: typeof HumanIdentityRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/settings': {
      id: '/human/settings'
      path: '/settings'
      fullPath: '/human/settings'
      preLoaderRoute: typeof HumanSettingsRouteImport
      parentRoute: typeof HumanRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/human': {
      id: '/login/human'
      path: '/login/human'
      fullPath: '/login/human'
      preLoaderRoute: typeof LoginHumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/verifier': {
      id: '/login/verifier'
      path: '/login/verifier'
      fullPath: '/login/verifier'
      preLoaderRoute: typeof LoginVerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier/activity': {
      id: '/verifier/activity'
      path: '/activity'
      fullPath: '/verifier/activity'
      preLoaderRoute: typeof VerifierActivityRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/dashboard': {
      id: '/verifier/dashboard'
      path: '/dashboard'
      fullPath: '/verifier/dashboard'
      preLoaderRoute: typeof VerifierDashboardRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/payments': {
      id: '/verifier/payments'
      path: '/payments'
      fullPath: '/verifier/payments'
      preLoaderRoute: typeof VerifierPaymentsRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/settings': {
      id: '/verifier/settings'
      path: '/settings'
      fullPath: '/verifier/settings'
      preLoaderRoute: typeof VerifierSettingsRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/verify': {
      id: '/verifier/verify'
      path: '/verify'
      fullPath: '/verifier/verify'
      preLoaderRoute: typeof VerifierVerifyRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents': {
      id: '/api/v1/agents'
      path: '/api/v1/agents'
      fullPath: '/api/v1/agents'
      preLoaderRoute: typeof ApiV1AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/credentials': {
      id: '/api/v1/credentials'
      path: '/api/v1/credentials'
      fullPath: '/api/v1/credentials'
      preLoaderRoute: typeof ApiV1CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/digilocker': {
      id: '/api/v1/digilocker'
      path: '/api/v1/digilocker'
      fullPath: '/api/v1/digilocker'
      preLoaderRoute: typeof ApiV1DigilockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/integrations': {
      id: '/api/v1/integrations'
      path: '/api/v1/integrations'
      fullPath: '/api/v1/integrations'
      preLoaderRoute: typeof ApiV1IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/transactions': {
      id: '/api/v1/transactions'
      path: '/api/v1/transactions'
      fullPath: '/api/v1/transactions'
      preLoaderRoute: typeof ApiV1TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human/credentials/': {
      id: '/human/credentials/'
      path: '/credentials'
      fullPath: '/human/credentials/'
      preLoaderRoute: typeof HumanCredentialsIndexRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/credentials/add': {
      id: '/human/credentials/add'
      path: '/credentials/add'
      fullPath: '/human/credentials/add'
      preLoaderRoute: typeof HumanCredentialsAddRouteImport
      parentRoute: typeof HumanRoute
    }
    '/verifier/agents/': {
      id: '/verifier/agents/'
      path: '/agents'
      fullPath: '/verifier/agents/'
      preLoaderRoute: typeof VerifierAgentsIndexRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/verifier/agents/$agentId': {
      id: '/verifier/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/verifier/agents/$agentId'
      preLoaderRoute: typeof VerifierAgentsAgentIdRouteImport
      parentRoute: typeof VerifierRoute
    }
    '/api/v1/agents/$agentId': {
      id: '/api/v1/agents/$agentId'
      path: '/$agentId'
      fullPath: '/api/v1/agents/$agentId'
      preLoaderRoute: typeof ApiV1AgentsAgentIdRouteImport
      parentRoute: typeof ApiV1AgentsRoute
    }
    '/api/v1/verify/age': {
      id: '/api/v1/verify/age'
      path: '/api/v1/verify/age'
      fullPath: '/api/v1/verify/age'
      preLoaderRoute: typeof ApiV1VerifyAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HumanRouteChildren {
  HumanActivityRoute: typeof HumanActivityRoute
  HumanDashboardRoute: typeof HumanDashboardRoute
  HumanIdentityRoute: typeof HumanIdentityRoute
  HumanSettingsRoute: typeof HumanSettingsRoute
  HumanCredentialsAddRoute: typeof HumanCredentialsAddRoute
  HumanCredentialsIndexRoute: typeof HumanCredentialsIndexRoute
}

const HumanRouteChildren: HumanRouteChildren = {
  HumanActivityRoute: HumanActivityRoute,
  HumanDashboardRoute: HumanDashboardRoute,
  HumanIdentityRoute: HumanIdentityRoute,
  HumanSettingsRoute: HumanSettingsRoute,
  HumanCredentialsAddRoute: HumanCredentialsAddRoute,
  HumanCredentialsIndexRoute: HumanCredentialsIndexRoute,
}

const HumanRouteWithChildren = HumanRoute._addFileChildren(HumanRouteChildren)

interface VerifierRouteChildren {
  VerifierActivityRoute: typeof VerifierActivityRoute
  VerifierDashboardRoute: typeof VerifierDashboardRoute
  VerifierPaymentsRoute: typeof VerifierPaymentsRoute
  VerifierSettingsRoute: typeof VerifierSettingsRoute
  VerifierVerifyRoute: typeof VerifierVerifyRoute
  VerifierAgentsAgentIdRoute: typeof VerifierAgentsAgentIdRoute
  VerifierAgentsIndexRoute: typeof VerifierAgentsIndexRoute
}

const VerifierRouteChildren: VerifierRouteChildren = {
  VerifierActivityRoute: VerifierActivityRoute,
  VerifierDashboardRoute: VerifierDashboardRoute,
  VerifierPaymentsRoute: VerifierPaymentsRoute,
  VerifierSettingsRoute: VerifierSettingsRoute,
  VerifierVerifyRoute: VerifierVerifyRoute,
  VerifierAgentsAgentIdRoute: VerifierAgentsAgentIdRoute,
  VerifierAgentsIndexRoute: VerifierAgentsIndexRoute,
}

const VerifierRouteWithChildren = VerifierRoute._addFileChildren(
  VerifierRouteChildren,
)

interface ApiV1AgentsRouteChildren {
  ApiV1AgentsAgentIdRoute: typeof ApiV1AgentsAgentIdRoute
}

const ApiV1AgentsRouteChildren: ApiV1AgentsRouteChildren = {
  ApiV1AgentsAgentIdRoute: ApiV1AgentsAgentIdRoute,
}

const ApiV1AgentsRouteWithChildren = ApiV1AgentsRoute._addFileChildren(
  ApiV1AgentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HumanRoute: HumanRouteWithChildren,
  VerifierRoute: VerifierRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  LoginHumanRoute: LoginHumanRoute,
  LoginVerifierRoute: LoginVerifierRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiV1AgentsRoute: ApiV1AgentsRouteWithChildren,
  ApiV1CredentialsRoute: ApiV1CredentialsRoute,
  ApiV1DigilockerRoute: ApiV1DigilockerRoute,
  ApiV1IntegrationsRoute: ApiV1IntegrationsRoute,
  ApiV1TransactionsRoute: ApiV1TransactionsRoute,
  ApiV1VerifyAgeRoute: ApiV1VerifyAgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
